version: "3"
services:
    dtcollector:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - DT_HOME=${DT_HOME}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - CUID=${CUID}
          - CGID=${CGID}
      container_name: "${DT_COLLECTOR_NAME}"
      image: "dynatrace/collector:7.0"
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_HOME
        - DT_SERVER_LICENSE_KEY_FILE_URL
        - DT_SERVER_NAME
        - APPMON_COLLECTOR_PORT
        - APPMON_ONEAGENT_NONSSL_PORT
        - APPMON_ONEAGENT_SSL_PORT
        - APPMON_COLLECTOR_SERVER_SSL_PORT
      volumes:
        - "${DT_COLLECTOR_LOG_PATH_ON_HOST}:${DT_HOME}/log/collector/dtcollector"
      networks:
        - appmon
      ports:
        # 9998 - Legacy Agent to Collector
        - "${APPMON_COLLECTOR_PORT:-9998}:9998"
        # 8042 One Agent to Collector non SSL
        - "${APPMON_ONEAGENT_NONSSL_PORT:-8042}:8042"
        # 8043 One Agent to Collector SSL
        - "${APPMON_ONEAGENT_SSL_PORT:-8043}:8043"
      user: "${CUID}:${CGID}"

networks:
    appmon:
        driver: bridge
