FROM keymetrics/pm2:18-alpine

ARG BACKEND_PORT=$BACKEND_PORT

# Bundle APP files
COPY . src/

# Install app dependencies
WORKDIR /src/

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

#EXPOSE ${BACKEND_PORT}

CMD ["npm", "run", "pm2-prod"]
