version: "2.1"
services:
    tomcat:
      container_name: tomcat
      image: tomcat
      ports:
        - 8080
      env_file:
        - ../../.env
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_AGENT_NAME=tomcat-agent
        - CATALINA_OPTS="-agentpath:${DT_HOME}${AGENT_LIB64}=name=tomcat-agent,collector=${DT_COLLECTOR_NAME}"
      volumes_from:
      - container:dtagent
      command: catalina.sh run

networks:
  default:
    external:
        name: ${COMPOSE_PROJECT_NAME}_appmon
