version: "2.1"
services:
    nginx:
      container_name: nginx
      image: nginx
      ports:
        - 80
      env_file:
        - ../../.env
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_AGENT_NAME=nginx-agent
        - LD_PRELOAD=${DT_HOME}${AGENT_LIB64}
      volumes_from:
        - container:dtagent
      command: sh -c "${DT_HOME}/run-wsagent.sh && nginx -g 'daemon off;'"

networks:
  default:
    external:
        name: ${COMPOSE_PROJECT_NAME}_appmon
