version: "3.7"

services:
  server-image:
    container_name: server_image
    build:
      context: ../../server-image
      dockerfile: Dockerfile
    environment:
      - IMAGE_SERVER_PORT=${IMAGE_SERVER_PORT}
      - IMAGE_SERVER_URL=${IMAGE_SERVER_URL}
#   ports:
#     - "${IMAGES_SERVER_PORT}:${IMAGES_SERVER_PORT}"
    volumes:
      - ../../server-image/:/src
      - node_modules_server_image:/src/node_modules			
    networks:
      - MyMeanStackNetwork
      - traefik-global-proxy   
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-global-proxy"
      - "traefik.http.routers.server-image-secure.entrypoints=websecure"
      - "traefik.http.routers.server-image-secure.rule=Host(`${IMAGE_SERVER_URL}`)"
      - "traefik.http.routers.server-image-secure.service=server-image"
      - "traefik.http.services.server-image.loadbalancer.server.port=${IMAGE_SERVER_PORT}" 
volumes:
# default dir on Ubuntu: /var/lib/docker/volumes
  node_modules_server_image: {}	
networks:
  traefik-global-proxy:
    external: true

