version: "3.7"

services:
  traefik:
    image: traefik:2.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - TraefikGlobalProxy
    ports:
#     - 80:80
      - 443:443
    environment:
      OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
      OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
      OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
      OVH_ENDPOINT: ${OVH_ENDPOINT} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../docker/conf/traefik/traefik.yml:/traefik.yml:ro
      - ../../docker/conf/traefik/configurations:/configurations
      - /dev/disk/by-id/google-traefiksslpd:/acme
      - ./letsencrypt:/letsencrypt
      - ./traefik/logs:/traefik/logs
      - ../../docker/conf/traefik/traefik-maintenance-plugin:/plugins-local/src/github.com/programic/traefik-maintenance-plugin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=TraefikGlobalProxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${FORGE_BASE_URL}`)"
#     - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
#     - "traefik.http.routers.traefik-secure.middlewares=ipwhitelist-for-socializus-tools@file" # we apply our middleware
networks:
  TraefikGlobalProxy:
    external: true

