version: "2.1"
services:
    httpd:
      container_name: httpd
      image: httpd
      ports:
        - 80
      env_file:
        - ../../.env
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_AGENT_NAME=httpd
        - DT_AGENT_COLLECTOR=${DT_COLLECTOR_NAME}
      volumes_from:
      - container:dtagent
      command: >
        sh -c " \
          ${DT_HOME}/run-wsagent.sh && \
          (echo LoadModule dtagent_module ${DT_HOME}${AGENT_LIB64} >> conf/httpd.conf) && \
          httpd-foreground"


networks:
  default:
    external:
        name: ${COMPOSE_PROJECT_NAME}_appmon
